### ISSUE TITLE
Módulo de mensajería: notificaciones instantáneas

### ISSUE THREAD

**Issue by manuartero** [JugadorNumero12/JugadorNum12#101]
### Notificaciones instantáneas

Suponiendo un sistema de mensajería privada entre usuarios, añadir un sistema de notificaciones instantáneas para una serie de casos.
Una _notificación_ será un mensaje privado con la peculiaridad que no tiene como origen ningún usuario del sistema ni se puede responder a él (sólo leerlo y archivarlo/borrarlo)
### Cuándo llegan las notificaciones

| Causa de la notificación | Quién recibe la notificación | Link en presente en el mensaje |
| :-- | :-- | :-- |
| Se ha completado una acción | Todos los miembros de la afición | Pantalla de inicio |
| Se ha terminado un partido | Todos los miembros de la afición | Pantalla de calendario |
| Un jugador ha contribuido en una acción grupal | El resto de participantes de la acción | Pantalla de la acción concreta |
| Una acción ha expirado por tiempo (no completa) | Los participantes de la acción | Pantalla inicio |
| Se abre una acción | Todos los miembros de la afición | Pantalla de la acción concreta |

**Comment by manuartero** [comment]
Se reabre la issue ya que las especificaciones sufren 2 cambios:
1.  Se eliminará el link del mensaje; es decir, de ahora en adelante las notificaciones no tendrán ningún enlace.
2.  Falta por añadir un botón de **_eliminar todas las notificaciones**_

**Comment by leximagination** [comment]
añadido boton de borrar todas las notificaciones y quitada la url
