### ISSUE TITLE
Retoque en la vista de perfil

### ISSUE THREAD

**Issue by manuartero** [JugadorNumero12/JugadorNum12#103]
### Descripción

En la vista del perfil, parece que _no hay acciones pasivas ni de partido desbloqueadas_

> Una opción sería si no hay nada , no mostrar ningún encabezado. Sencillamente no habría `div` y ya está

---

![Captura](https://f.cloud.github.com/assets/2211052/366269/8e907036-a27c-11e2-99bc-392769d1b73a.JPG)

**Comment by Argaide** [comment]
No veo el problema manu. Explícate más por favor

**Comment by manuartero** [comment]
Lo siento, no existe el fallo, sencillamente confundí los dos títulos con uno sólo **_no tienes nada desbloqueado; por cierto estas son tos habilidades desbloqueadas**_

De todas formas, voy a cambiar de _bug_ a _revisión_ porque si me ha pasado a mi creo que le puede pasar a un usuario.

**Comment by manuartero** [comment]
Esta _issue_ hace tiempo que se completó pero no se cerró.
