### ISSUE TITLE
Imágenes con demasiada resolución

### ISSUE THREAD

**Issue by DiegoGal** [JugadorNumero12/JugadorNum12#108]
Al elegir entre Animadora, Empresario y Ultra, las imágenes que salen tienen demasiada resolución para el pequeño tamaño que ocupan, y esto hace que sea lenta la carga de la página.

Estaría bien ajustar la resolución de las imágenes al tamaño que ocupan

**Comment by manuartero** [comment]
Cierro esta _issue_ porque estamos trabajando en ella, junto con otras medidas para mejorar la velocidad de carga en la _issue_ #131
