### ISSUE TITLE
Fechas para jugar partidos

### ISSUE THREAD

**Issue by DiegoGal** [JugadorNumero12/JugadorNum12#110]
Se puede asistir a un partido de una fecha pasada.

**Comment by manuartero** [comment]
Hemos intentado asistir a un partido pasado y no creemos que haya fallo. Lo que sí se puede hacer es ver una pantalla de resumen (crónica, resultado y detalles) de un partido pasado... pero no _asistir_ a él.

Si la _issue_ se refiere a la pantalla de "resumen de un partido pasado" la cerraremos.

**Comment by manuartero** [comment]
Hemos comprobado que _jugar_ un partido pasado es imposible. Lo que si es posible es ver la _crónica_ de partidos pasados.

Se cierra la _issue_
