### ISSUE TITLE
Errores/sugerencias aportados por FrozenWars

### ISSUE THREAD

**Issue by danilc91** [JugadorNumero12/JugadorNum12#113]
Lo primero deciros que esto es sobre la versión de la última presentación, no se si algunos errores ya los habéis solucionado o no.

-Estaría bien que al registrarte te metiera directamente en la web.

-Que al comprar no me lleve a mis habilidades, porque quizás quiero seguir comprando y luego elegir las que voy a usar.

-Debería haber unas instrucciones de juego.

-Si abrimos dos ventanas de iniciar sesión en el mismo explorador e inciamos con una cuenta y en la otra nos registramos, en la que hemos creado no me deja iniciar sesión NUNCA. Creo que pretendéis que sea como facebook, que no se pueda iniciar sesión en el mismo explorador con distintas cuentas, pero deberías controlar este error.

-La cuenta que he creado anteriormente no me funciona. User: frozenwars2 pass: frozenwars2. Podeis meteros y ver la pantalla siniestra que sale, si creo otra cuenta normalmente, no da ningún problema. 

-Podrías desactivar el boton usar cuando la habilidad esté en cooldown y poner un contador para saber cuanto le queda. También con la influencia.

-En internet explorer no funciona el botón superior derecho, no salen bien las opciones de sign out y perfil. Y al cambiar de equipo no cambia el color de ese botón.

-No se cual es el objetivo real del juego, si me puedo cambiar de equipo constantemente, ¿quién me interesa que gane y por qué? ¿O es que, cambiar de equipo solo sirve para ayudar al equipo que me interese para indirectamente ayudar al que realmente elegí al principio?¿Es por eso que al cambiar de equipo no cambia el color de arriba a la derecha?

Espero que os sea de ayuda, si tenéis algo que preguntarme sobre lo que os he escrito, preguntad a frozenwars por Dani López.

**Comment by Darkhogg** [comment]
Sería interesante que abriérais VARIAS issues, una por cada error, para así poder ir arreglándolos uno a uno, por diferentes miembros, y cerrarlos poco a poco.

**Comment by danilc91** [comment]
Tienes razón, ya lo he hecho, espero que os sirva de ayuda.

**Comment by Darkhogg** [comment]
Gracias. :)
Cierro esta issue entonces.
