### ISSUE TITLE
Sugerencia: Incómodo registrarse e iniciar sesión

### ISSUE THREAD

**Issue by danilc91** [JugadorNumero12/JugadorNum12#114]
-Estaría bien que al registrarte te metiera directamente en la cuenta.

**Comment by manuartero** [comment]
En la reunión del **12 de mayo** acordamos eliminar el correo de confirmación por lo que el flujo de registro quedaría exactamente igual que la petición:
- Registro en la página
- Redirección al índice de la página

> Asignado @Ltreaper

**Comment by Ltreaper** [comment]
Cierro issue. Esta funcionalidad ha sido incorporada.
