### ISSUE TITLE
Sugerencia: Incómodo a la hora de comprar

### ISSUE THREAD

**Issue by danilc91** [JugadorNumero12/JugadorNum12#115]
-Que al comprar no me lleve a mis habilidades, porque quizás quiero seguir comprando y luego elegir las que voy a usar.

**Comment by manuartero** [comment]
El flujo al desbloquear y utilizar habilidades ha sido reestructurado. Además, se está trabajando en la _issue_ #98 creando _puntos de desbloqueo_ al subir de nivel.

> Seguir la _issue_ #98
