### ISSUE TITLE
Sugerencia: Instrucciones. Página de ayuda

### ISSUE THREAD

**Issue by danilc91** [JugadorNumero12/JugadorNum12#116]
-Debería haber unas instrucciones de juego.
-No se cual es el objetivo real del juego, si me puedo cambiar de equipo constantemente, ¿quién me interesa que gane y por qué? ¿O es que, cambiar de equipo solo sirve para ayudar al equipo que me interese para indirectamente ayudar al que realmente elegí al principio?¿Es por eso que al cambiar de equipo no cambia el color de arriba a la derecha?

**Comment by manuartero** [comment]
Muevo la petición al _milestone_ **6. Demo de mayo** y trabajaremos sobre ella

**Comment by manuartero** [comment]
Se asigna a @Argaide a resolver la _issue_. En la reunión del **12 de mayo** se decide hacer vistas de **_ayuda**_ o **_instrucciones**_ en lugar de tutorial.

**Comment by manuartero** [comment]
##### _Issue_ hecha por @Argaide
