### ISSUE TITLE
Error en internet explorer

### ISSUE THREAD

**Issue by danilc91** [JugadorNumero12/JugadorNum12#117]
-En internet explorer no funciona el botón superior derecho, no salen bien las opciones de sign out y perfil. Y al cambiar de equipo no cambia el color de ese botón.

**Comment by Darkhogg** [comment]
Internet Explorer no es una prioridad. Primero que funcione en exploradores decentes, y ya nos dedicaremos si hay tiempo a guarrear código para IE.

**Comment by rootpayload** [comment]
Propongo matarle por el bien del gremio.
