### ISSUE TITLE
Sugerencia: ver los cooldowns.

### ISSUE THREAD

**Issue by danilc91** [JugadorNumero12/JugadorNum12#118]
-Podríais desactivar el boton usar cuando la habilidad esté en cooldown y poner un contador para saber cuanto le queda. También con la influencia.

**Comment by manuartero** [comment]
Deshabilitar el botón si la acción no está disponible: trabajando en ello para el _milestone_ **5 demo de abril**; issue: #130 

No comprendemos bien qué quieres decir con también la influencia.

**Comment by manuartero** [comment]
**Mostrar cooldown** : Trabajando en ello #130 y #153 
**Mostrar tiempo restante en habilidades de partido** : No se va a implementar
