### ISSUE TITLE
Error: cuenta creada no funciona (dobles pestañas)

### ISSUE THREAD

**Issue by danilc91** [JugadorNumero12/JugadorNum12#119]
-Si abrimos dos ventanas de iniciar sesión en el mismo explorador e inciamos con una cuenta y en la otra nos registramos, en la que hemos creado no me deja iniciar sesión NUNCA. Creo que pretendéis que sea como facebook, que no se pueda iniciar sesión en el mismo explorador con distintas cuentas, pero deberías controlar este error.

-La cuenta que he creado anteriormente no me funciona. User: frozenwars2 pass: frozenwars2. Podeis meteros y ver la pantalla siniestra que sale, si creo otra cuenta normalmente, no da ningún problema.

**Comment by manuartero** [comment]
Sobre el usuario que no existe, se debe a que aún estamos haciendo pruebas en el servidor y hemos borrado el contenido de las tablas de la base de datos. 

Sobre la posibilidad de abrir dos ventanas en un mismo navegador, estudiaremos la propuesta.

**Comment by manuartero** [comment]
Etiquetamos la _issue_ como wontfix ya que no se va a implementar que el juego funcione sobre dos pestañas sobre el mismo navegador.

> Ver el documento https://github.com/JugadorNumero12/JugadorNum12/blob/develop/funcionalidades_excluidas.md
