### ISSUE TITLE
Regeneración de influencias

### ISSUE THREAD

**Issue by rootpayload** [JugadorNumero12/JugadorNum12#120]
Añadir una columna en la tabla de generación de recursos que indique las influencias bloqueadas en acciones.

Actualizarla cuando se realicen/participe en acciones.

Desbloquearla cuando se termine una acción.

Modificar el script de generación de recursos para que solo incremente las influencias no bloqueadas.

**Comment by manuartero** [comment]
Cierrro la _issue_ por estar duplicada. 

## Su número es la #126
