### ISSUE TITLE
Bug : primer partido de liga generado

### ISSUE THREAD

**Issue by manuartero** [JugadorNumero12/JugadorNum12#127]
Existe un desbarajuste en los datos presentes en la base de datos y los datos mostrados en distintas vistas.
- **_El nivel de los equipos**_ mostrado en las vistas no coincide con el nivel real.

Además, el primer partido de liga de cualquiera de los equipos cuenta con **_aforo**_ 0 y **_nivel del equipo**_ incorrecto

Es muy posible que este fallando el algoritmo de generar encuentros únicamente para el primer partido. 

> También revisaría el archivo `datos.sql` para cargar un valor de **_nivel de equipo**_ y **_aforo básico**_ para todos los equipos

**Comment by rootpayload** [comment]
No entiendo por que falla solo el primero, todos se generan igual.

**Comment by rootpayload** [comment]
He metido los datos cuando se gneran los partidos, pero insito en que pueden cambiar hasta que este empiece, espero que en el primer turno se actualicen.
