### ISSUE TITLE
Bug de partido: Ejecución de dos partidos continuados

### ISSUE THREAD

**Issue by manuartero** [JugadorNumero12/JugadorNum12#129]
Durante la demo del _22 de abril_ se ejecutaron de forma continuada dos partidos entre los mismos equipos (posiblemente se enlazaron el último turno del primero con el primer turno del segundo).

Dado que sólo ha ocurrido una vez en todas las pruebas; y la base de datos se tocó durante las pruebas, la _issue_ se marca como **_revisión**_.

> Tanto LTReaper como K2Rober seguirán la evolución de este error

**Comment by Ltreaper** [comment]
Existe una opción viable para lo sucedido, aunque muy extraña:
- Al spamear acciones de partido durante el primer turno, como son transacciones, tomaron todas el control de sus transacciones sin permitir al partido ejecutar la suya. Esto provocó que, al minuto siguiente, el cron no viese cambios en el partido y creyese que aún no se estaba ejecutando, cuando, en memoria, ya había comenzado. 
  Se pudieron mantener los partidos en algún turno en memoria por este motivo y al final se generaron varias notificaciones/partidos paralelos.
  Esto se soluciona con turnos más largos (para lo que está diseñado el sistema) y, salvo que se permita a la gente un límite bestial de recursos, no debería suceder de nuevo.
  Cierro la issue momentáneamente y , en caso de resurgir durante la demo de hoy, se revisará con más cautela.
