### ISSUE TITLE
Mejora en las habilidades: deshabilitar el uso en cooldown

### ISSUE THREAD

**Issue by manuartero** [JugadorNumero12/JugadorNum12#130]
Cuando un jugador no pueda usar una habilidad debido a su _cooldown_, deshabilitar (o no mostrar) el botón de _usar_.

**Comment by leximagination** [comment]
falta ver el cooldown

**Comment by manuartero** [comment]
Se reorganiza al _milestone 6_.

> Participan: @PedroMorgado  @leximagination  y @MarcosAlarconRivas
