### ISSUE TITLE
Rendimiento del servidor: Compilación previa de los archivos .less

### ISSUE THREAD

**Issue by manuartero** [JugadorNumero12/JugadorNum12#131]
Compilar en cada recarga todo el código `.less` para pasarlo a código `.css` es realmente costoso; hace falta para las versiones estables precompilar los archivos antes de subirlos al servidor.

Además, las imágenes de fondo de acuarela son extremadamente pesadas; sería necesario rebajarlas la calidad.

> Esta _issue_ engloba también a la #108

**Comment by Darkhogg** [comment]
El commit que hay justo encima de este comentario (9a8823f) añade la carga automática de los ficheros CSS si la aplicación está en modo desarrollo (`YII_DEBUG` es `false` o no está definido). De paso, añade todos los ficheros CSS compilados de los LESS que tenía en ese momento.
**No hay ningún proceso automático que convierta los LESS en CSS por lo que, antes de subir cualquier cambio al servidor, ha de compilarse todo el LESS.** Excepto esta vez, que lo he hecho yo. A menos que alguien haga más cambios posteriormente, claro.

Ah, sí, y alguien tendrá que desactivar `YII_DEBUG`. Probablemente @Ltreaper.

**Comment by Ltreaper** [comment]
Gracias por la aportación, he testeado el proceso y funciona correctamente. Cierro la issue realizada por @Darkhogg
