### ISSUE TITLE
Datos del partido: crónica y detalles

### ISSUE THREAD

**Issue by manuartero** [JugadorNumero12/JugadorNum12#133]
Completar la vista de partido: 
- **Detalles**: valores de las variables que están influyendo en el partido en el turno en juego. Remarcar qué valores son de qué equipo.
- **Crónica**. mostrar la crónica que se está generando en el partido.

> La carga de trabajo se repartirá entre _MarcosAlarconRivas_ y _Darkdog_

**Comment by rootpayload** [comment]
Esta hecho, a falta de revisión.

**Comment by Ltreaper** [comment]
Completado y revisado. He agregado recarga por ajax.
