### ISSUE TITLE
Chat : restringir 1 chat por partido

### ISSUE THREAD

**Issue by manuartero** [JugadorNumero12/JugadorNum12#134]
Un chat deberá ser privado de cada partido. Es decir, si se juegan dos partidos simultáneos, no podrán compartir la misma ventana de chat.

Además, a la hora de gestionar la tabla de mensajes de chat, hay que hacer distinciones entre partidos.

> Nota: Añadir a la tabla del chat el id del partido al que pertenece

**Comment by samuelmgalan** [comment]
Añadido id al chat (no 123 como hasta ahora), que es el id del partido en juego. Como 2 partidos simultáneos no van a compartir id, los chats son independientes. No hace falta añadir un campo más a la base de datos.
