### ISSUE TITLE
Bug en participar en acción: Bucle de redireccionamiento

### ISSUE THREAD

**Issue by Argaide** [JugadorNumero12/JugadorNum12#135]
Al participar en una acción (aportar recursos) me ha dado en un bucle de redireccionamiento

**Comment by rootpayload** [comment]
A mi me acaba de pasar lo mismo.
Tenía dos acciones abiertas (pintarse con los colores del equipo y organizar homenaje) en las que solo había participado yo.

Le he dado a participar en pintarse y he añadido 400 de animo, más de lo que hacia falta para rellenar el animo total de la accion, pero todabía faltaba dinero e infulencia.

Me ha dado un bucle de redireccion y me ha borrado las 2 acciones abiertas.

**Comment by manuartero** [comment]
Creo que el fallo sólo concierne a la habilidad **_pintarse con los colores del equipo**_

**Comment by PedroMorgado** [comment]
Completada!
