### ISSUE TITLE
Funcionalidad del partido: recargar las acciones de partido por AJAX

### ISSUE THREAD

**Issue by manuartero** [JugadorNumero12/JugadorNum12#137]
En la vista de partido, añadir `AJAX` para recargar los recursos y las acciones de partido

**Comment by Ltreaper** [comment]
Ambas completadas y testeadas

**Comment by manuartero** [comment]
Al subirlo al servidor, el 25 de abril, esta funcionalidad fallo; hace falta revisarla

**Comment by Ltreaper** [comment]
Comprobado que funciona la recarga por ajax de recursos. Lo que pasa es que en ciertos momento se puede demorar un poco. Eso no se puede controlar, ya que es una transacción y lleva un par de segundos. Existe un retraso entre la ejecución de la grupal y la actualización de la barra superior.
IMPORTANTE: al no poder recargar la barra superior sólo se actualiza el numerillo, no la barra trasera. 
Si en las pruebas de esta noche vuelve a fallar, reabriré la issue.
