### ISSUE TITLE
Vistas: Añadir footer

### ISSUE THREAD

**Issue by manuartero** [JugadorNumero12/JugadorNum12#143]
Añadir a todas las vistas de la página un _footer_ al final de la página.

Información a mostrar:
- Información de contacto (correo de gmail)
- Enlace a página de arte de la página (sin hacer)
- Enlace a la página elegida por el artista => **lobonleal.blogspot.com.es**
- Nombrar a la complutense (por decidir)

> Hasta que se cree la _página de arte_ mostrar un enlace ficticio

**Comment by samuelmgalan** [comment]
Cuando se sepa, se podría poner aquí la página del artista.

**Comment by manuartero** [comment]
**_lobonleal.blogspot.com.es**_
