### ISSUE TITLE
Vista de partido : Integrar los dibujos del artista

### ISSUE THREAD

**Issue by manuartero** [JugadorNumero12/JugadorNum12#144]
Añadir a la vista del partido los dibujos de jugadores de futbol. 

Cargar el dibujo correspondiente según
- el estado del partido
- el equipo que está jugando (cambiarán los colores de la imagen)

> Participa también en la _issue_ @arturpareja  y @manutero

**Comment by Darkhogg** [comment]
Invoco a @arturpareja para que me cuente cómo va el tema de los dibujos.
