### ISSUE TITLE
Revisión del archivo <datos.sql>

### ISSUE THREAD

**Issue by arturpareja** [JugadorNumero12/JugadorNum12#16]
- Dónde se encuentra el bug:
  Archivo: datos.sql, tabla acciones grupales, columna jugador_acc
  Ejemplo: acción grupal con id_accion=2
- Cómo solucionarlo:
  hay que cambiar a mano ese valor, comparándolo con el número de jugadores que hay en la tabla Participaciones

**Comment by manuartero** [comment]
El archivo `datos.sql` pronto va a ser reescrito ya que los datos de ejemplo para hacer pruebas ya vamos a **borrarlos**.

Por lo tanto, cambio el Issue de **_bug**_ a **_debugging**_. Lo que hay que hacer es eliminar los datos iniciales de:
1. acciones_grupales
2. acciones_individuales
3. desbloqueadas
4. participaciones
5. partidos; _atención_ no borrar el contenido de esta tabla hasta que se haya terminado un script que la rellene con datos reales.
6. recursos; _atención_ no borrar el contenido de esta tabla hasta que se haya terminado un script que la rellene con datos reales.

Por lo tanto, las tablas que se mantienen con datos iniciales son.
1.  usuarios
2. equipos
3. clasificación; _atención_ pendiente de revisión.

**Comment by samuelmgalan** [comment]
A pesar de lo que dice manutero (ya que para la demo vamos a usar el archivo acctual), creo que ahora mismo son consistentes los datos entre Participaciones y Acciones Grupales, no?

**Comment by arturpareja** [comment]
Han pasado a ser consistentes en cuanto se arregló que el número de participantes inicialmente fuese 0 y no 1, porque siempre contaba 1 más de los que había en la lista. Además cuando adquieres una grupal, todavía no has participado en ella, solamente te la "bajas".

Todavía queda el vaciado de las tablas para cerrar la Issue.

**Comment by samuelmgalan** [comment]
No entiendo lo del vaciado de las tablas.

**Comment by manuartero** [comment]
EL archivo `datos.sql` sólo contiene los equipos que formarán la liga y algunos usuarios iniciales. Ya no es necesario revisar su consistencia
