### ISSUE TITLE
Documentación: Diagrama de clases UML

### ISSUE THREAD

**Issue by manuartero** [JugadorNumero12/JugadorNum12#18]
Documentación práctica pedida por Sámer: **diagrama de clases UML** del proyecto

**Comment by Argaide** [comment]
Sam Mendez también participó

**Comment by manuartero** [comment]
Cierro el issue por **_Argaide**_

La carpeta de `Drive` con los diagramas es: https://drive.google.com/?authuser=0#folders/0B80G8C57fZdxRy1fX2NyU0N2VVU
