### ISSUE TITLE
Funcionalidad del partido: iniciar un partido

### ISSUE THREAD

**Issue by manuartero** [JugadorNumero12/JugadorNum12#21]
Script que provoca la llamada a `scripts/ejecutarturno` en el momento marcado por la hora de inicio del partido

**Comment by Ltreaper** [comment]
Finalmente creado con cron de Yii/crontab de Linux.
Hay que revisar la implementación por eficiencia pero actualmente funciona en el servidor.
Doy por cerrada esta Issue. En caso de revisión , se abrirá una nueva.
