### ISSUE TITLE
Funcionalidad de partido: mostrar el partido en tiempo real

### ISSUE THREAD

**Issue by manuartero** [JugadorNumero12/JugadorNum12#22]
Mostrar por la vista del partido la evolución en tiempo real. No es necesario aplicar ningún estilo a los datos mostrados. 
Al final del partido mostrar la crónica total generada así como el resultado final.

**Comment by Argaide** [comment]
Hecho. La vista del partido está hecha y se actualiza automáticamente cuando se pasa de turno

**Comment by manuartero** [comment]
la vista está completa a falta de añadirle estilo
