### ISSUE TITLE
Ajuste de recursos iniciales en nuevos usuarios

### ISSUE THREAD

**Issue by Ltreaper** [JugadorNumero12/JugadorNum12#24]
##### Ajustar recursos iniciales al crear personaje.

Es necesario que, cuando un usuario se registre en la página, tenga una serie de recursos iniciales. Basta con ponerlos aproximadamente, no tienen que ser milimétricos. Pero sí, al menos, que permitan un mínimo de funcionalidad al entrar.

> Es posible que sea necesaria la coordinación entre este issue y el de fijar recursos y atributos de las habilidades (acciones).

**Comment by samuelmgalan** [comment]
Hecho: Los valores máximos los he puesto en función de los que tenemos propios. Los valores actuales están por debajo de los nuestros actuales, pero con algo empiezan. La generación es la misma (como no hay niveles oficialmente...).
Si estás de acuerdo se puede cerrar.

**Comment by Ltreaper** [comment]
Cerrada.
