### ISSUE TITLE
Ajuste de recursos consumidos/proporcionados por las acciones

### ISSUE THREAD

**Issue by Ltreaper** [JugadorNumero12/JugadorNum12#25]
#### Estimar recursos consumidos/generados
- Es necesario estimar aproximadamente los recursos que consumen y generan las distintas acciones (habilidades). 
- También es necesario calcular un poco mejor (o hacerlos variados) los cooldowns y finalizaciones de las mismas. Para evitar dudas, el cooldown indicará en las acciones individuales cúanto tiempo (en segundos) pasará entre que un usuario ejecuta la accion individual A y puede volver a ejecutar dicha acción. El tiempo de finalización de una grupal indicará de cúanto tiempo (en segundos) se dispone desde su creación para completarla. Si se ha pasado ese tiempo y está incompleta, pasará a ser deshechada (esto lo hace otro script del controlador ScriptsController.php).

> Es posible que sea necesaria la coordinación de esta función con alguna otra de ajuste de recursos.

**Comment by manuartero** [comment]
Terminado. 

#### Falataría por hacer un documento resumen en el que se recogan todos los costes / efectos para la documentación del proyecto
