### ISSUE TITLE
Revisión de participar en grupales

### ISSUE THREAD

**Issue by Ltreaper** [JugadorNumero12/JugadorNum12#26]
#### Revisión de participar en grupales

Es necesario revisar la función de participar en una acción grupal por completo. En principio parece que la funcionalidad es correcta, pero este issue es para comprobar esto al 100%.

> Dado que se están tocando actualmente las acciones de ejecutar una grupal, no es aconsejable el testeo de la función de Participar creando antes una grupal. Para evitar colisiones de debugging/implementación, se recomienda participar en acciones modificando la base de datos con los datos necesarios para las pruebas. Incluso se puede hacer una copia de datos.sql en el escritorio (o donde queráis), modificarla para vuestras necesidades, y debuggear en base a dicha copia adicional.

**Comment by samuelmgalan** [comment]
Creo que se puede dar por cerrada, no?

**Comment by Ltreaper** [comment]
Se cierra pendiente de debugging completo.
