### ISSUE TITLE
Revisión de relaciones en modelos

### ISSUE THREAD

**Issue by Ltreaper** [JugadorNumero12/JugadorNum12#27]
#### Revisión de las relaciones de modelos

Es necesario revisar las relaciones establecidas entre modelos y asegurarse de su coherencia y correcta implementación. En principio deberían funcionar todas sin problema, pero nunca está de más un repaso ya que otra persona puede ver fallos que yo no he visto.

> Por favor, compararlas con calma con la base de datos para buscar incoherencias.

**Comment by manuartero** [comment]
Esta _issue_ queda fuera de la planificación del curso

> Ver el documento https://github.com/JugadorNumero12/JugadorNum12/blob/develop/funcionalidades_excluidas.md
