### ISSUE TITLE
Revisión de reglas en modelos

### ISSUE THREAD

**Issue by Ltreaper** [JugadorNumero12/JugadorNum12#28]
#### Revisión de las reglas de los modelos

Necesario un repaso a las funciones "rules" de los modelos que verifican los atributos con lo establecido en la base de datos. 

> Los campos con <lista_campos>, 'required' no son estrictamente necesarios. De hecho, es mejor dejarlos como están (eliminando campos que no existan en la BBDD, eso si) ya que, de agregar todos los campos marcados como "not null" en la base de datos, por ejemplo, podría dar algún problema. De todas formas, el que lo revise que lo haga asegurándose de que es correcto. 
> Lo que sí es más importante es la verificacion de que los tipos de datos concuerdan con los de la BBDD.

**Comment by manuartero** [comment]
Esta _issue_ queda fuera de la planificación del curso. 

> Ver el documento https://github.com/JugadorNumero12/JugadorNum12/blob/develop/funcionalidades_excluidas.md
