### ISSUE TITLE
Script para ejecutar funcionalidad continuamente

### ISSUE THREAD

**Issue by Ltreaper** [JugadorNumero12/JugadorNum12#29]
#### Script de ejecución

Necesario un script que permita ejecutar continuamente (de hecho, realizar una llamada a una función de Yii como si se tratase de una API) de forma continuada. Esto es: como si fuese un while (true) que se ejecutase toda la vida y que, en caso de excepción o error, pueda volver a lanzarse de nuevo para no detener la funcionalidad.

> Como ayuda a esto, tengo ejemplos de algun script PHP para ello, pero habría que revisarlo y adaptarlo a nuestras necesidades.
> Este script será usado para permitir la continua revisión de las acciones grupales e individuales (si han acabado y hace falta devolverles recursos o han finalizado sin éxito). Esta última funcionalidad está implementada, pero falta el script que permita mantenerla en funcionamiento.

---
#### Aplicaciones inmediatas del script
1. Finalizar acciones individuales
2. Finalizar acciones grupales incompletas (expiradas en el tiempo)
3. Actualizar recursos a los jugadores.

**Comment by Darkhogg** [comment]
¿Esto no se haría en script que ejecuta cron?

**Comment by Ltreaper** [comment]
La idea es tener un script/daemon/etc que ejecute una funcionalidad continuamente. El cron solo permite hacerlo con un espacio mínimo de 1 segundo y permite solapar scripts (y hay que evitar esto).
Muy por encima, sería como hacer un programa con un while(true) infinito.

**Comment by Darkhogg** [comment]
El problema es que hay muy pocos servidores que admitan eso, y PHP es un lenguaje muy malo para ese tipo de cosas...
Aparte, impedir que dos cron solapen es "fácil" de hacer usando un fichero candado.

**Comment by Ltreaper** [comment]
Bien, en ese caso se admite cualquier método que querais para ello. Lo importante es la funcionalidad que se quiere conseguir.

**Comment by manuartero** [comment]
Añadidos los 3 casos principales para los que necesitamos esta funcionalidad

**Comment by Ltreaper** [comment]
Doy por cerrada esta issue. No se ha hecho con script sino con actualización continua en las acciones.
