### ISSUE TITLE
Reajuste de la fórmula 

### ISSUE THREAD

**Issue by Ltreaper** [JugadorNumero12/JugadorNum12#30]
#### Reajustar la fórmula del partido

En caso de ser necesario, dar los retoques a esta fórmula para permitir unos partidos lo más equilibrados posible.

> Es posible que haya  que compaginarlo con la persona que esté ajustando los datos de efectos de acciones.

**Comment by ka2rober** [comment]
Reajustada la formula.Ya hay goles en los partidos y se juegan partidos lo mas reales posibles dependiendo del valor de los atributos que hayan obtenido los dos equipos.
