### ISSUE TITLE
Adjuntar previa y asistencia de partidos

### ISSUE THREAD

**Issue by Ltreaper** [JugadorNumero12/JugadorNum12#32]
#### Previa/asistencia de partidos
- Previa: hay que agregar un enlace a todos los encuentros de la lista de partidos que permita ver la previa (en caso de ser el próximo partido y no haber empezado), la crónica final del partido (en caso de que ya haya acabado) o un aviso de que no es el próximo partido del equipo (en caso de ir a un partido que no concuerde con los casos anteriores). Para ello ese enlace llamará a la función actionPrevia del controlador PartidosController y éste se encargará de transmitir los datos necesarios.
- Asistir: agregar botón de asistencia a la previa (en caso de no existir) y habilitarlo tanto ahí como en la lista de partidos sólo si el encuentro se está jugando (turnos 1-11. Usar constantes declaradas en la clase Partido apropiadamente en vez del 1 y el 11).

> Lo importante es que haya ese enlace a la previa del partido si es el siguiente y aún no ha comenzado y poder ver las crónicas de partidos ya jugados. Asimismo, otra opción es que el botón de Previa cambie a Asistir cuando el partido esté en juego. La funcionalidad final será parecida. Hay que tratar de simplificarlo lo máximo posible de cara al usuario.

**Comment by ka2rober** [comment]
Todo lo que pone en esta issue lo acabo de comprobar y de terminar lo que faltaba, así que doy por acabada esta issue.
