### ISSUE TITLE
Formato en página de registro

### ISSUE THREAD

**Issue by Ltreaper** [JugadorNumero12/JugadorNum12#34]
#### Formatear página de registro

Es necesario dar un formato más adecuado a los avisos que salen cuando los datos en registro son incorrectos. Ahora mismo salen letras bastante grandes y no es muy apropiado.

**Comment by arturpareja** [comment]
Tanto en el formulario de login como en el formulario de registro, he sacado los errores en un div separado con su propio estilo (fondo rojo transparente y bordes redondeados). Cierro el Issue.
