### ISSUE TITLE
Script de generacion de temporadas

### ISSUE THREAD

**Issue by Ltreaper** [JugadorNumero12/JugadorNum12#35]
#### Script de temporadas

Necesario un script que genere una temporada completa en función de todos los equipos de la base de datos.

**Comment by rootpayload** [comment]
Ya esta hecho, cuidado con un delatlle:
el script, se llama con horas GMT+0

Yo me he estado rayando un webo por no darme cuenta.

**Comment by Argaide** [comment]
Me acabo de bajar las cosas de develop y no veo ningún partido en el calendario de partidos. ¿Es normal?

**Comment by Argaide** [comment]
Ademas me da fallo en la vista usuarios/ver porque intenta acceder la la variable $proximopartido que no existe

**Comment by rootpayload** [comment]
Lo primero si, es normal, si llamas a JugadorNum12/scripts/liga se generan.
Lo segundo es un error en la vista que debería tener en cuenta que no haya partidos planeados.

**Comment by Argaide** [comment]
Ok. Ya cambie la vista así que no hay problema
