### ISSUE TITLE
Documentación: Diagramas de flujo

### ISSUE THREAD

**Issue by manuartero** [JugadorNumero12/JugadorNum12#38]
Documentación útil pedida por Sámer: **_diagramas de flujo**_ del proyecto,

> El grupo de trabajo es _LTreaper_ y _manutero_

**Comment by Ltreaper** [comment]
Finalizados los diagramas básicos. Cierro esta issue. Si falta alguno o hay errores que se puedan reparar sin reabrir, se hará así. En caso de que sean errores graves, reabrir issue.
