### ISSUE TITLE
Documentación: Diagrama de casos de uso

### ISSUE THREAD

**Issue by manuartero** [JugadorNumero12/JugadorNum12#39]
Documentación práctica pedida por Sámer: **diagrama de los casos de uso**.

Comprenderá también la revisión de los casos de uso actuales ya que están desfasados o incorrectos.

Subir el resultado en una carpeta situada en la ráiz del proyecto llamada `documentacion`

> Participantes en la _issue_ : @arturpareja @Ltreaper @leximagination

**Comment by manuartero** [comment]
#### Reorganización:
- Se mueve al _milestone 6_ 
- Se encarga de ella a partir de ahora @leximagination

**Comment by Ltreaper** [comment]
Finalizados los diagramas por @leximagination . Cierro esta issue. Al igual que el resto de documentación, cualquier cambio menor será llevado a cabo sin necesidad de reapertura de la issue.
