### ISSUE TITLE
Documentación 1º cuatrimestre: listado del grupo

### ISSUE THREAD

**Issue by manuartero** [JugadorNumero12/JugadorNum12#41]
Texto literal de la revisión del profesor.

> 1. Ponerme una lista de miembros del grupo (no uséis nicknames), que no la he visto
>    por ningún sitio :(
> 2. Un enlace claro donde ver lo que ha hecho cada uno y las horas
>    dedicadas a la semana (aproximado pero “basado en hechos reales”). En vuestro
>    caso el GIT sirve no solo para ver la calidad del código, sino el reparto de tareas.
>    Supuestamente allí me debería aclarar lo que ha hecho cada uno, pero para
>    aclararme necesito que os pongáis con el nombre completo tanto en la
>    documentación (GoogleDocs) como en el código (GitHub). 
> 3. Por lo que he llegado a ver, hay quien ha hecho poco o nada a nivel de código (Xaby López 0 de 583 commits, Arturo Pareja 16 de 583 commits, etc.)

**Comment by Ltreaper** [comment]
Lista agregada en el documento de "Miembros, planificación y reparto de tareas". Falta completar las horas llevadas a cabo por cada miembro, pero eso ha sido abierto en otras issues"
