### ISSUE TITLE
Documentación del 1º cuatrimestre: motivación del proyecto

### ISSUE THREAD

**Issue by manuartero** [JugadorNumero12/JugadorNum12#43]
Texto literal de la revisión del profesor.

> 1. Echo en falta algún tipo de introducción/visión del proyecto al comienzo de la
>    documentación. Os ponéis a hablar del juego pero no contáis porque hacer un juego,
>    la motivación que hay detrás, etc.

**Comment by Ltreaper** [comment]
Creada motivación básica del proyecto en el documento de "Definición del juego", tras la explicación básica del enfoque del mismo.
Cierro la issue. En caso de ser necesario mover esa motivación a otro documento, puede hacerse con total libertad pero manteniendo la coherencia entre las referencias del indice.

**Comment by Ltreaper** [comment]
Pasada motivación al documento de "Introducción al proyecto"
