### ISSUE TITLE
Documentación del 1º cuatrimestre: Investigación de proyectos similares

### ISSUE THREAD

**Issue by manuartero** [JugadorNumero12/JugadorNum12#44]
Texto copiado literal de la revisión del profesor.

> 1. Se echa en falta investigación: analizar proyectos y productos parecidos al vuestro,
>    que contéis la parte de brainstorming, las cosas que considerasteis al principio...

**Comment by Ltreaper** [comment]
Creado todo en el documento "Introducción al proyecto". Issue cerrada.
