### ISSUE TITLE
Documentación del 1º cuatrimestre: planificación global en Gantter

### ISSUE THREAD

**Issue by manuartero** [JugadorNumero12/JugadorNum12#45]
Texto copiado literal de la revisión del profesor.

> 1. Necesito una planificación formal mínima (me parece bien lo que tenéis en GitHub,
>    pero pasarlo a formato documento, al menos). Y también ponerme ese Gantter global
>    que hicisteis al principio, aunque luego lo habéis desechado... que sirva como
>    planificación global.

**Comment by Ltreaper** [comment]
Fragmentado Gantter con Photoshop y agregado al documento de "Miembros, planificación y reparto de tareas".
