### ISSUE TITLE
Documentación del 1º cuatrimestre: revisión de las referencias en los documentos

### ISSUE THREAD

**Issue by manuartero** [JugadorNumero12/JugadorNum12#47]
Texto copiado literal de la revisión del profesor.

> 1. Las referencias que ponéis en los documentos deben ser completas, no una URL
>    suelta, sino que debéis poner el autor y el nombre de los documentos, etc.

**Comment by Ltreaper** [comment]
Revisadas las referencias existentes. Ahora llevan el nombre del autor/autores y el título del documento. En el caso de las URL, se ha agregado información acerca de la compañía a la que pertenecen y, en caso de estar disponible, el nombre del autor/es.
