### ISSUE TITLE
Revisión de las vistas: <head> y código php 

### ISSUE THREAD

**Issue by manuartero** [JugadorNumero12/JugadorNum12#56]
Dos puntos:
1. Eliminar cualquier declaración de `head` en cualquier vista que no sea `/layouts/main.php` . En concreto la vista del _perfil_ tiene declarada una sección de cabecera.
2. En la medida de lo posible, eliminar código funcional (como por ejemplo consultas a la base de datos) de las vistas.  En concreto el archivo `layouts/main.php`. Para ello, habrá que pasar al layout los datos desde el controlador.

**Comment by Darkhogg** [comment]
Arreglado entre @PedroMorgado y yo en la rama `Estilo`.
Se cerrará en cuanto mezclemos con `develop`.
