### ISSUE TITLE
Apartado visual: Registro en 3 etapas

### ISSUE THREAD

**Issue by manuartero** [JugadorNumero12/JugadorNum12#57]
Actualmente el registro es un único formulario en el que se introducen:
1. Email
2. Contraseña y confirmación de la contrasela 
3. Afición a la que pertenecer
4. Personaje escogido

Esto se va a dividir en 3 pasos diferenciasdos.

**Primer paso**
1. Email
2. Contraseña y confirmación de la contrasela 

**Segundo paso**
3. Afición a la que pertenecer

**Tercer paso**
4. Personaje escogido

**Comment by arturpareja** [comment]
Completado el registro en 3 etapas, además se han cambiado los formularios de Equipo y Personaje para que el usuario los seleccione pulsando sobre el escudo o el personaje directamente (con funciones JQuery).

**Comment by manuartero** [comment]
Reabro esta _issue_ para indicar que los dibujos se han reducido en exceso.

**Comment by manuartero** [comment]
#### Reorganización
- Se mueve al _milestone 6_
- Se encargará de cerrarla @Ltreaper 

#### Resumen de lo que queda por hacer
- El peso en Mb de las imágenes del login es excesivo. Hay que solucionarlo. 
- Imágenes demasiado pequeñas (opcional)
