### ISSUE TITLE
Apartado visual: Revisión de la parte visual del login

### ISSUE THREAD

**Issue by manuartero** [JugadorNumero12/JugadorNum12#60]
#### Colocación general

Dividir la pantalla del login en dos `div` de igual tamaño.

En cada div, el área reservada para texto ocupa 1/3 del alto total.
#### fondo sombreado para resaltar el texto

Ahora mismo, el texto no se lee bien. Vamos a mantener el color blanco del texto pero pondremos un fondo gris para el texto de la izquierda y el formulario de la derecha.
El fondo tendrá opacidad < 1 (quizá en torno al 0.4), es decir dejará ver el fondo.
#### El cuadrado de los formularios

Aplicar estilo al formualrio: poner del mismo estilo que otros cuadrados de texto de la página.
#### Mover el botón de registro al área del formulario

![login](https://f.cloud.github.com/assets/2211052/231942/e4c0d4fa-871a-11e2-9b42-6d6413dce72a.png)

**Comment by arturpareja** [comment]
El estilo del Login lo he dejado lo más parecido posible a como se pide, aunque aún se admiten mejoras. Cierro el Issue.
