### ISSUE TITLE
Bug: vista duplicada

### ISSUE THREAD

**Issue by manuartero** [JugadorNumero12/JugadorNum12#68]
Cargar los datos de pruebas iniciales
Logearse como manu
Pinchar desbloqueadas
Usar _Crearse espectativas_

Ahora la vista está duplicada

**Comment by samuelmgalan** [comment]
A mi no me pasa.
Lo he hecho con usuario "manu" y me sale un mensajito de que la acción ha terminado. Así que no está duplicada.

**Comment by manuartero** [comment]
Lo acabo de probar y ahora no es que me salga duplicada, sino que me da un fallo (sigue siendo bug)

Me he asegurado de actualizarme completamente en la rama `develop`

He cargado el archivo `estructura.sql`

He cargado el archivo `datos.sql`

se me muestra esto:
![Captura](https://f.cloud.github.com/assets/2211052/255466/6cd4c79c-8c0d-11e2-80ba-a7b98ea60811.JPG)
![Captura2](https://f.cloud.github.com/assets/2211052/255467/6ce8082a-8c0d-11e2-8db8-f941f799f26f.JPG)

**Comment by samuelmgalan** [comment]
Ese es el error general, el if de Rober.

**Comment by samuelmgalan** [comment]
Arreglado por Rober.
