### ISSUE TITLE
Mejora en la participación en acciones: mostrar aviso

### ISSUE THREAD

**Issue by manuartero** [JugadorNumero12/JugadorNum12#69]
Lanzar un aviso después de participar en la acción ¿ha tenido éxito? ¿cuánto falta ahora para completarla? ¿con mi contribución se ha completado?

**Comment by leximagination** [comment]
Se han añadido las notificaciones para comprobar si has aportado algo a la acción o si no has aportado nada, si has completado la acción o si ya está completada
