### ISSUE TITLE
Mejora en la participación en acciones: información extra

### ISSUE THREAD

**Issue by manuartero** [JugadorNumero12/JugadorNum12#70]
Al participar en una acción grupal actualmente sale un formulario para introducir nuevos recursos. Hay que mostrar más información:
1.  Cambiar el orden de los recursos para que coincida con el orden general.
2.  Mostrar cuántos recursos se han apostado hasta el momento sobre el total, por ejemplo `influencias: 4/12`. Estaría muy bien que se mostrase con el mismo formato con el que se muestran los recursos en la barra de recursos (la barra gris)
3.  Mostrar cuántos participantes hay ya en la acción

**Comment by samuelmgalan** [comment]
1. Donde hay que cambiar el orden de los recursos es en la vista anterior a Participar, no en esa. (cambiado)
2. Hecho sin las barras grises (es un script, es rizar el rizo un poco)
3. Hecho
