### ISSUE TITLE
Revisión de los recursos: influencias

### ISSUE THREAD

**Issue by manuartero** [JugadorNumero12/JugadorNum12#71]
A lo largo de la prueba del 13 de marzo, nos hemos dado cuenta que el recurso influencia está completamente desequilibrado. 

Una opción **temporal** que arreglaría todos los problemas sería multiplicar **100** veces el coste en influencia de las acciones (no el coste de bajarlas sino el coste de completarlas)

**Comment by samuelmgalan** [comment]
Cambiadas en `datos.sql` las tablas `acciones_grupales` (solo las completadas), `habilidades` y `participaciones` para conseguir el efecto deseado.
