### ISSUE TITLE
Mejora: mensajes de error 404

### ISSUE THREAD

**Issue by manuartero** [JugadorNumero12/JugadorNum12#72]
Cambiar todos los mensajes de error `404` que redirigen a la página del login por mensajes flash.

**Comment by leximagination** [comment]
mensajes flash o notificaciones?¿

**Comment by manuartero** [comment]
Olvida los mensajes Flash, hay que ir cambiando todos por las ventanitas emergentes que estás haciendo

**Comment by leximagination** [comment]
cambiados todos los CHttpException(404, ... ) por notificaciones
habría que cambiar también las Exception ( ... , 40x ) de PartidosController?¿

**Comment by leximagination** [comment]
la funcionalidad es algo rara después de haberlo cambiado

te situas en participar en una acción grupa, y participas cuando ya ha expirado el tiempo, entonces muestra las siguientes notificaciones:

Acción inexistente, habilidad inexistente ...

**Comment by samuelmgalan** [comment]
Acabo de verlo y me gusta el tema notificación, pero si que quedan un poco feas en blanco. Se pueden quitar automáticamente o hay que darle a la X si o si?

**Comment by leximagination** [comment]
hay que darle a la x

**Comment by manuartero** [comment]
Damos por cerrado este Issue
