### ISSUE TITLE
Experencia del usuario: crear una acción grupal

### ISSUE THREAD

**Issue by manuartero** [JugadorNumero12/JugadorNum12#75]
Al crear una acción grupal, el usuario cuenta como el primer participante  de dicha acción.
¿por qué el sistema me pregunta si no quiero participar cuando ya estoy participando?

**Comment by samuelmgalan** [comment]
Si no entiendo mal, lo que se quiere es que no pregunte si quieres participar, no? Simplemente te informa de los recursos que has gastado al usarla y listo.
Es decir, quitar el botón Participar de la vista.

**Comment by samuelmgalan** [comment]
Efectivamente, se eliminó el botón Participar al usar una acción, y el botón Aceptar te redirije a la acción que acabas de usar, no al index de acciones como antes. Lo doy por finalizado.
