### ISSUE TITLE
Revisión de funcionalidad: reparto de ánimo tras acabar el partido

### ISSUE THREAD

**Issue by manuartero** [JugadorNumero12/JugadorNum12#77]
Necesario revisar que se reparta `ánimo` tras un partido a los jugadores de los equipos que han participado.

**Comment by Ltreaper** [comment]
Confirmo que el ánimo se reparte correctamente. De hecho, puntualizo diciendo que me ha llenado la barra (50 puntos) completamente.
Doy por cerrada la issue ya que el reparto no falla. En todo caso se podría ajustar en un futuro.
