### ISSUE TITLE
Apartado visual: Pantalla de partido

### ISSUE THREAD

**Issue by manuartero** [JugadorNumero12/JugadorNum12#79]
> El equipo de trabajo para esta _issue_ es 
> 1. Daniel Escoz
> 2. Pedro Morgado
> 3. Arturo Pareja

---
### Estructurar la vista

Utilizar el esquema al que se llegó en la reunión del 3 de abril

![Esquema - visual - partido](https://f.cloud.github.com/assets/2211052/348612/be065a54-9f68-11e2-9a2f-f0db86887870.png)
#### Cuadro para imagen:

Contactar con el artista para que facilite las imágenes deseadas.
#### Cuadro para el marcador y la información estática

Información estática (siempre presente)
1. Tiempo del partido
3. Marcador
4. Equipos enfrentados
5. Nivel de ambos equipos
6. Aforo
7. Ambiente

> Eliminado el tiempo restante del turno
#### Ventana de partido

Por medio de _tabs_ esta ventana se divide en 4 vistas:
1. Descripción gráfica del pártido
2. Detalles de los valores numéricos internos
3. Crónica generada
4. Chat

**Comment by manuartero** [comment]
Esta Issue queda anulada para el milestone _2 Demo de marzo_ y se aplaza al _4 Demos de abril_

**Comment by Darkhogg** [comment]
Por favor, @arturpareja y @PedroMorgado (y yo): En el comentario de TODOS los commits que tengan que ver conesta issue, debería salir mencionada dicha issue. Para ello simplemente tiene que aparecer un `#79` en algún punto del comentario de commit.

**Comment by manuartero** [comment]
Se ha decidido dejar únicamente 1 reloj de partido, **eliminando el reloj que marca el tiempo de 1 turno**

**Comment by Darkhogg** [comment]
Se me olvidó mencionar esto en los últimos commits, pero ya hay sistema anti-spam con cooldowns y esas cosas.
