### ISSUE TITLE
Completar la barra superior

### ISSUE THREAD

**Issue by Darkhogg** [JugadorNumero12/JugadorNum12#85]
Completar del todo la barra superior, incluyendo:
- Mostrar los recursos en sus colores correspondientes
- Mostrar tu nombre, avatar (personaje) y menú de usuario
- Mostrar un logotipo a la izquierda

**Comment by Darkhogg** [comment]
Nombre, avatar y menú de usuario hechos. Falta mostrar el avatar correcto.

**Comment by PedroMorgado** [comment]
- Mostrar los recursos del usuario
- Mostrar logotipo a la izquierda
