### ISSUE TITLE
Módulo de experiencia: crear el sistema de niveles

### ISSUE THREAD

**Issue by manuartero** [JugadorNumero12/JugadorNum12#98]
### Base de datos
- Modificar la estructura de la base de datos para que soporte la acumulación de experiencia.
- Actualizar el registro de nuevos usuarios para que sea coherente con la nueva estructura
- Añadir _puntos de desbloqueo_
### Obtener experiencia y subir de nivel
- Añadir la funcionalidad de obtener experiencia
- Añadir la funcionalidad para subir de nivel (curva _exponencial_)
### Puntos de desbloqueo
- Subir un nivel se traduce en ganar 1 punto de compra de habilidades
- Implementar un sistema de canjeo de puntos de experiencia por habilidades

**Comment by manuartero** [comment]
Se reabre la issue ya que al llegar a un nivel, se pueden desbloquear todas las acciones de dicho nivel. 

Hace falta generar unos puntos de **_desbloqueo**_ con los que desbloquear acciones

**Comment by PedroMorgado** [comment]
Terminada.
